[34m[1mwandb[0m: [33mWARNING[0m wandb.init() arguments ignored because wandb magic has already been initialized
Traceback (most recent call last):
  File "newSNN.py", line 48, in <module>
    X, y = load_data()
  File "newSNN.py", line 38, in load_data
    "/home/blackfalcon/gitstuff/Detecting-Spoof-Emails-with-Information-Fusion/Dataset/vscode"
FileNotFoundError: [Errno 2] No such file or directory: '/home/blackfalcon/gitstuff/Detecting-Spoof-Emails-with-Information-Fusion/Dataset/vscode'
>>> 