[34m[1mwandb[0m: [33mWARNING[0m wandb.init() arguments ignored because wandb magic has already been initialized
5574
1393
1394
5972
importing data...
Traceback (most recent call last):
  File "start.py", line 26, in <module>
    import Machinelearning
  File "/home/blackfalcon/gitstuff/Detecting-Spoof-Emails-with-Information-Fusion/Prototype/Machinelearning.py", line 98, in <module>
    unknown_data = get_list_spam(file2)
  File "/home/blackfalcon/gitstuff/Detecting-Spoof-Emails-with-Information-Fusion/Prototype/Machinelearning.py", line 79, in get_list_spam
    msg = TextBlob(tabsep[1])
IndexError: list index out of range
