[34m[1mwandb[0m: [33mWARNING[0m wandb.init() arguments ignored because wandb magic has already been initialized
Traceback (most recent call last):
  File "emailNN.py", line 48, in <module>
    X, y = load_data()
  File "emailNN.py", line 38, in load_data
    "C:/Users/Admin/Documents/GitHub/Detecting-Spoof-Emails-with-Information-Fusion/Dataset/Legit.csv"
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Admin/Documents/GitHub/Detecting-Spoof-Emails-with-Information-Fusion/Dataset/Legit.csv'
